### ISSUE TITLE
There is a problem on Android side

### ISSUE THREAD

**Issue by nuriulgen** [engineer-unknown/watermark_unique#1]
It works smoothly on iOS devices, but I get this error on the Android side and I can't build.

“ * What went wrong:
A problem occurred configuring project ':watermark_unique'.
> Could not open cp_proj generic class cache for build file '/Users/****/.pub-cache/hosted/pub.dev/watermark_unique-1.0.1/android/build.gradle' (/Users/*****/.gradle/caches/7.6.3/scripts/31j50r97x7cmidhwb3bblqygg).
   > Build file '/Users/*****/.pub-cache/hosted/pub.dev/watermark_unique-1.0.1/android/build.gradle' should not contain a package statement.
> Failed to notify project evaluation listener.
   > Could not get unknown property 'android' for project ':watermark_unique' of type org.gradle.api.Project.
   > Could not get unknown property 'android' for project ':watermark_unique' of type org.gradle.api.Project."

I use the package like this:

```
final watermarkPlugin = WatermarkUnique();
        final watermarkedImagePath = await watermarkPlugin.addImageWatermark(
          filePath: imageFile.path, // image file path
          watermarkImagePath: watermarkFile.path, // watermark image file path
          x: dstX, // position by x
          y: dstY, // position by x
          quality: 100, // quality of image with watermark
          imageFormat: ImageFormat.png, // image format that you will use to compress
          watermarkWidth: scaledWidth, // watermark image width
          watermarkHeight: scaledHeight, // watermark image height
        );
```

**Comment by engineer-unknown** [comment]
Hey @nuriulgen ! Thanks for sharing a problem. I am going to fix it as soon as possible.

**Comment by nuriulgen** [comment]
@engineer-unknown  I am eagerly waiting for the problem to be resolved as soon as possible.

**Comment by engineer-unknown** [comment]
@nuriulgen The Issue was fixed and updated to pub.dev. Thanks for your time!

**Comment by nuriulgen** [comment]
@engineer-unknown  The problem seems to be solved, thank you for solving the problem so quickly.
