### ISSUE TITLE
Feature Suggestions for Watermark Plugin: Adaptive Font Size, Auto Wrapping, and Background Transparency Control

### ISSUE THREAD

**Issue by Xorn4400** [engineer-unknown/watermark_unique#5]
Dear Maintainers,

First and foremost, thank you for developing and maintaining this watermark plugin, which has significantly facilitated our image processing tasks. In the course of application, I've identified a few functional enhancements that could further improve user experience. I am hereby proposing the following suggestions:

Adaptive Font Size Based on Image Resolution

Currently, the size of the watermark text is fixed, which can lead to varying visual effects across images with different resolutions. I propose introducing an option to automatically adjust the watermark text size based on the dimensions of the image, ensuring a consistent and aesthetically pleasing appearance across all image sizes.

Automatic Text Wrapping

When the watermark text is lengthy, the ability to wrap the text automatically when it reaches the boundary would prevent truncation or obscuring important parts of the image. This feature would be particularly beneficial for watermarks containing multiple lines of information.

Enhanced Compatibility for Background Transparency Control

I encountered an issue when attempting to pass a background transparency value from Flutter, due to discrepancies in the long data type range between Flutter and Android platforms. I suggest refining the plugin to seamlessly handle transparency values passed from Flutter, ensuring cross-platform consistency and reliability.

I believe these improvements will broaden the plugin's applicability and user base. If needed, I am also willing to provide further testing feedback or assistance. I look forward to your consideration and once again, thank you for your diligent work!

Environment Information:

- Flutter Version:3.19.3
- Plugin Version:1.0.2
- Testing Device/Simulator: android

**Comment by engineer-unknown** [comment]
Hey! Thanks for suggesting improvements. I will take a look at soon as possible!

**Comment by engineer-unknown** [comment]
@Xorn4400 I was add an Auto Wrapping and Background Transparency Control for now.  But for Adaptive Font Size I will skip it for some time. Maybe in future, I will add it. 

New version is available on the pub.dev: 1.0.5

**Comment by momoohidayat** [comment]
I don't see background transparency, even though i add `.withOpacity(0.5)`

*update:
i found the fix:
`UIRectFillUsingBlendMode(backgroundRect, .normal)`
