### ISSUE TITLE
Multiline Text Rendering Changes from Version 0.0.6 to 1.0.3

### ISSUE THREAD

**Issue by HasanAlqaisi** [engineer-unknown/watermark_unique#6]
Hi
Previously, using version 0.0.6, multiline text displayed correctly. However, after updating to version 1.0.3, the text now appears as a single line. This issue was also noticed in the example app. 
For instance, entering 
```dart 
'''Test watermark text Test
watermark text Test watermark 7''' 
```
 in the new version results in single line rendering.
 I am not sure in which version the issue started because I updated the package directly to 1.0.3

**Comment by HasanAlqaisi** [comment]
I see that `addTextWatermarkUint8List` was using dart code on version 0.0.6 which allowed the multi line text to be rendered correctly. And now it is depending on the native code and that's why the text rendering is different.

**Comment by engineer-unknown** [comment]
Hey @HasanAlqaisi ! Thanks for your reply. I will fix it as soon as possible

**Comment by engineer-unknown** [comment]
@HasanAlqaisi  The issue was fixed and updated for pub.dev.  Also i added automatic text wrapping. So now you can use \n for multiline

**Comment by HasanAlqaisi** [comment]
Thanks for the quick fix!
I did a quick test and I see that Automatic text wrapping is working but not the multiline issue.

- When (text length > image width), automatic wrapping works but not the multiline
- When (text length < image width), the text will be rendered in one line although I have \n within the text

**Comment by engineer-unknown** [comment]
Okay, thanks! I will fix it

**Comment by engineer-unknown** [comment]
@HasanAlqaisi  Did you use IOS / Android or Web for testing?

**Comment by engineer-unknown** [comment]
@HasanAlqaisi  Okay, i found the issue and just fixed it. The new version is available on the pub.dev
